name: Execução Diária do robô

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  executar:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Commit do relatório
      run: |
        git conf user.name "github-actions"
        git add dados/relatorio.csv
        git commit -m "Atualização diaria"
        git push
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
       
